<a href="https://colab.research.google.com/github/fmlorilla/Linear-discriminant-Analysis-LDA-for-Wine-Dataset/blob/master/LDA_CSP%20Youtube.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [143]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [144]:
df = pd.read_excel('/CS_CSP.xlsx')
df

,Control Strategy,Dish Diameter,Rated System Output (kW),Thermal/CollectorEfficiency/Concentrator Efficiency,Steady System Efficiency (%),Tracking Style,ST Accuracy
0,0,4.800,28.00,73.00,9.60,0,0.57
1,0,5.000,13.00,72.00,10.70,1,0.17
2,0,17.000,52.50,78.90,23.10,0,0.01
3,0,11.000,25.00,88.10,29.00,0,0.01
4,0,7.500,10.00,82.00,18.00,1,0.15
5,0,10.000,30.20,77.40,17.00,0,0.15
6,0,6.700,14.28,78.00,20.00,0,0.15
7,0,11.300,50.00,86.00,12.53,0,0.15
8,0,10.764,25.30,95.00,23.38,0,0.15
9,0,8.500,10.00,82.00,18.00,1,0.15
10,0,8.500,10.85,85.00,22.25,0,0.15
11,0,8.500,11.00,85.00,29.00,0,0.15
12,0,25.000,50.00,90.00,19.14,0,0.03
13,0,17.700,38.80,95.00,25.30,0,0.15
14,0,12.000,30.00,95.00,32.00,0,0.01
15,1,11.000,25.00,70.00,10.70,0,0.14
16,1,10.570,20.80,89.00,25.40,0,0.20
17,1,6.600,23.30,67.00,25.00,0,0.13
18,1,11.000,24.40,91.00,32.00,0,0.05
19,1,25.230,125.00,90.00,30.00,0,0.01
20,1,8.480,0.74,82.15,21.44,0,0.28
21,1,4.580,9.25,82.84,21.44,0,0.15
22,2,12.000,72.50,76.00,21.44,0,0.05
23,2,11.000,96.50,94.00,21.44,0,0.01
24,2,9.600,7.50,78.00,19.00,1,0.14
25,2,0.800,35.00,65.00,30.00,0,0.10
26,2,11.000,11.00,82.84,24.50,0,0.15
27,2,7.000,13.50,77.00,14.00,0,0.60
28,2,9.000,28.00,88.00,29.00,0,0.15
29,2,5.000,25.00,90.00,9.03,1,0.15

In [145]:
for i in df.columns:
    print(df[i].value_counts())

0    15
2     8
1     7
Name: Control Strategy, dtype: int64
11.000    5
8.500     3
5.000     2
12.000    2
4.800     1
10.570    1
7.000     1
0.800     1
9.600     1
4.580     1
8.480     1
25.230    1
6.600     1
17.700    1
25.000    1
10.764    1
11.300    1
6.700     1
10.000    1
7.500     1
17.000    1
9.000     1
Name: Dish Diameter, dtype: int64
25.00     3
28.00     2
10.00     2
50.00     2
11.00     2
23.30     1
35.00     1
7.50      1
96.50     1
72.50     1
9.25      1
0.74      1
125.00    1
24.40     1
30.00     1
20.80     1
13.00     1
38.80     1
10.85     1
25.30     1
14.28     1
30.20     1
52.50     1
13.50     1
Name: Rated System Output (kW), dtype: int64
95.00    3
90.00    3
82.00    2
78.00    2
85.00    2
82.84    2
73.00    1
91.00    1
77.00    1
65.00    1
94.00    1
76.00    1
82.15    1
70.00    1
67.00    1
89.00    1
72.00    1
86.00    1
77.40    1
88.10    1
78.90    1
88.00    1
Name: Thermal/CollectorEfficiency/Concentrator Efficiency, dtype: int64
21.44    4
29.00    3
32.00    2
18.00    2
30.00    2
10.70    2
9.60     1
14.00    1
24.50    1
19.00    1
25.00    1
25.40    1
19.14    1
25.30    1
22.25    1
23.38    1
12.53    1
20.00    1
17.00    1
23.10    1
9.03     1
Name: Steady System Efficiency (%), dtype: int64
0    25
1     5
Name: Tracking Style, dtype: int64
0.15    13
0.01     5
0.14     2
0.05     2
0.57     1
0.17     1
0.03     1
0.20     1
0.13     1
0.28     1
0.10     1
0.60     1
Name: ST Accuracy, dtype: int64

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Control Strategy                                     30 non-null     int64
 1   Dish Diameter                                        30 non-null     float64
 2   Rated System Output (kW)                             30 non-null     float64
 3   Thermal/CollectorEfficiency/Concentrator Efficiency  30 non-null     float64
 4   Steady System Efficiency (%)                         30 non-null     float64
 5   Tracking Style                                       30 non-null     int64
 6   ST Accuracy                                          30 non-null     float64
dtypes: float64(5), int64(2)
memory usage: 1.8 KB

In [147]:
df.describe()

,Control Strategy,Dish Diameter,Rated System Output (kW),Thermal/CollectorEfficiency/Concentrator Efficiency,Steady System Efficiency (%),Tracking Style,ST Accuracy
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,0.766667,10.237467,30.547333,82.841000,21.446333,0.166667,0.148667
std,0.858360,5.311427,27.170771,8.352566,6.739376,0.379049,0.135716
min,0.000000,0.800000,0.740000,65.000000,9.030000,0.000000,0.010000
25%,0.000000,7.125000,11.500000,77.550000,18.000000,0.000000,0.062500
50%,0.500000,9.800000,25.000000,82.840000,21.440000,0.000000,0.150000
75%,1.750000,11.000000,33.800000,89.750000,25.375000,0.000000,0.150000
max,2.000000,25.230000,125.000000,95.000000,32.000000,1.000000,0.600000

In [148]:
# selecting all the features within our dataset
features = df[['Dish Diameter', 'Rated System Output (kW)', 'Thermal/CollectorEfficiency/Concentrator Efficiency','Steady System Efficiency (%)', 'Tracking Style', 'ST Accuracy']] 
features = features.to_numpy() # converts feature set to numpy array
target = df['Control Strategy'].to_numpy() # converts target column to numpy array
features.shape, len(target)

((30, 6), 30)

In [149]:
# function for standardizing data
def standardScaler(feature_array):
  total_cols = feature_array.shape[1] # total number of columns 
  for i in range(total_cols): # iterating through each column
        feature_col = feature_array[:, i]
        mean = feature_col.mean() # mean stores mean value for the column
        std = feature_col.std() # std stores standard deviation value for the column
        feature_array[:, i] = (feature_array[:, i] - mean) / std # standard scaling of each element of the column

In [150]:
standardScaler(features) # performing standardization on our feature set 

# checking if standardization worked
total_cols = features.shape[1] # total number of columns 
for i in range(total_cols):
    print(features[:, i].std())

1.0000000000000002
1.0
0.9999999999999999
1.0
1.0
1.0

In [151]:
# creating randomized weights for our linear predictor func
weights = np.random.rand(3, 6)
# creating randomized biases for our linear predictor func
biases = np.random.rand(3, 1)

In [152]:
def linearPredict(featureMat, weights, biases):
  logitScores = np.array([np.empty([3]) for i in range(featureMat.shape[0])]) # creating empty(garbage value) array for each feature set
    
  for i in range(featureMat.shape[0]): # iterating through each feature set
        logitScores[i] = (weights.dot(featureMat[i].reshape(-1,1)) + biases).reshape(-1) # calculates logit score for each feature set then flattens the logit vector 
    
  return logitScores

In [153]:
features = df[['Dish Diameter', 'Rated System Output (kW)', 'Thermal/CollectorEfficiency/Concentrator Efficiency','Steady System Efficiency (%)', 'Tracking Style', 'ST Accuracy']] 
features = features.to_numpy() # converts feature set to numpy array
logitTest = linearPredict(features, weights, biases)
logitTest.shape

(30, 3)

In [154]:
def softmaxNormalizer(logitMatrix):
  probabilities = np.array([np.empty([3]) for i in range(logitMatrix.shape[0])]) 

  for i in range(logitMatrix.shape[0]):
        exp = np.exp(logitMatrix[i]) # exponentiates each element of the logit array
        sumOfArr = np.sum(exp) # adds up all the values in the exponentiated array
        probabilities[i] = exp/sumOfArr # logit scores to probability values
  return probabilities

In [155]:
def multinomialLogReg(features, weights, biases):
  logitScores = linearPredict(features, weights, biases)
  probabilities = softmaxNormalizer(logitScores)
  predictions = np.array([np.argmax(i) for i in probabilities]) #returns the outcome with max probability
  return probabilities, predictions

In [156]:
probabilities, predictions = multinomialLogReg(features, weights, biases)
print(probabilities.shape)
print(predictions)

(30, 3)
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [157]:
def accuracy(predictions, target):
  correctPred = 0
  for i in range(len(predictions)):
        if predictions[i] == target[i]:
            correctPred += 1
  accuracy = correctPred/len(predictions)*100
  return accuracy

accuracy = accuracy(predictions, target) #calculating accuracy for our model
print(accuracy)

23.333333333333332

In [158]:
def train_test_split(dataframe, test_size = 0.1):
    data = dataframe.to_numpy() # converts dataframe to numpy array
    totalRows = data.shape[0] # total rows in the dataset
    testRows = np.round(totalRows * test_size) # total rows in testing dataset
    randRowNum = np.random.randint(0, int(totalRows), int(testRows)) # randomly generated row numbers
    testData = np.array([data[i] for i in randRowNum]) # creates test dataset
    data = np.delete(data, randRowNum, axis = 0) # deletes test data rows from main dataset; making it training dataset
    train_features = data[:, :-1]
    train_target = data[:, -1]
    test_features = testData[:, :-1]
    test_target = testData[:, -1]
    
    return train_features, train_target, test_features, test_target    

# running train_test_split for our dataset
train_features, train_target, test_features, test_target = train_test_split(df, test_size = 0.17)
standardScaler(train_features) # standard scaling training set 
standardScaler(test_features) # standard scaling testing set
train_features.shape, train_target.shape, test_features.shape, test_target.shape

((25, 6), (25,), (5, 6), (5,))

In [159]:
def crossEntropyLoss(probabilities, target):
  n_samples = probabilities.shape[0]
  CELoss = 0
  for sample, i in zip(probabilities, target):
        CELoss += -np.log(sample[i])
  CELoss /= n_samples
  return CELoss

In [160]:
def stochGradDes(learning_rate, epochs, target, features, weights, biases):
    target = target.astype(int)
    loss_list = np.array([]) #initiating an empty array
    
    for i in range(epochs):
        probabilities, _ = multinomialLogReg(features, weights, biases) # Calculates probabilities for each possible outcome
        
        CELoss = crossEntropyLoss(probabilities, target) # Calculates cross entropy loss for actual target and predictions
        loss_list = np.append(loss_list, CELoss) # Adds the CELoss value for the epoch to loss_list
        
        probabilities[np.arange(features.shape[0]),target] -= 1 # Substract 1 from the scores of the correct outcome
        
        grad_weight = probabilities.T.dot(features) # gradient of loss w.r.t. weights
        grad_biases = np.sum(probabilities, axis = 0).reshape(-1,1) # gradient of loss w.r.t. biases
        
        #updating weights and biases
        weights -= (learning_rate * grad_weight)
        biases -= (learning_rate * grad_biases)
        
    return weights, biases, loss_list

In [161]:
updatedWeights, updatedBiases, loss_list = stochGradDes(0.1, 5000, train_target, train_features, weights, biases)

In [162]:
testProbabilities, testPredictions = multinomialLogReg(test_features, updatedWeights, updatedBiases)

correctPreds = 0
for i in range(len(testPredictions)):
    if testPredictions[i] == test_target[i]:
        correctPreds += 1
acc = correctPreds / len(testPredictions) * 100
print("Model accuracy on test dataset - {}".format(acc))

Model accuracy on test dataset - 0.0